#!/usr/bin/env bash

WORKING_PATH=$(pwd -P) # no tailing slash
SCRIPT_PATH=$(
  cd "$(dirname "$0")"
  pwd -P
) # no tailing slash
SCRIPT_VERSION='1.3.1'
SCRIPT_VERSION_NAME='Koffing '  # https://en.wikipedia.org/wiki/List_of_generation_I_Pok%C3%A9mon
C_VERSION="\033[38;5;99m"       # http://colors.sh/
C_RED="\033[38;5;9m"
C_GRN="\033[38;5;28m"
C_ORN="\033[38;5;202m"
C_OFF="\033[0m"

source ${SCRIPT_PATH}/app/db_import.sh
source ${SCRIPT_PATH}/app/deactivate_plugins.sh
source ${SCRIPT_PATH}/app/display_help_mssg.sh
source ${SCRIPT_PATH}/app/license_keys.sh
source ${SCRIPT_PATH}/app/print_version.sh
source ${SCRIPT_PATH}/app/process_flags.sh
source ${SCRIPT_PATH}/app/readable_time.sh
source ${SCRIPT_PATH}/app/replace_url.sh
source ${SCRIPT_PATH}/app/set_passwords.sh
source ${SCRIPT_PATH}/app/setup_connection_vars.sh
source ${SCRIPT_PATH}/app/sync_files.sh
source ${SCRIPT_PATH}/app/sync_uploads.sh
source ${SCRIPT_PATH}/app/update_wp_config.sh
source ${SCRIPT_PATH}/app/validate_variables.sh

ARG_SYNC_UPLOADS=0
ARG_SYNC_DB=9
ARG_SYNC_FILES=9

process_flags $@
setup_connection_vars
validate_variables

#license_keys
#exit #stop;

SYNC_START_TIME=$(date +%s)

# File SYNC
if [[ ${ARG_SYNC_FILES} == 1 ]]; then
  sync_files
fi

# Database & Extras sync.
if [[ ${ARG_SYNC_DB} == 1 ]]; then
  db_import
  update_wp_config
  deactivate_plugins
  replace_url
  set_passwords
  license_keys
fi

SYNC_END_TIME=$(date +%s)
echo -e "Sync took: ${C_ORN}$(readable_time $((SYNC_END_TIME - SYNC_START_TIME)))${C_OFF}"

# Uploads
if [[ ${ARG_SYNC_UPLOADS} == 1 ]]; then
  echo 'Syncing uploads, This might take a while.'
  echo 'The rest of the sync is done and usable.'
  sync_uploads
  SYNC_UPLOAD_TIME=$(date +%s)
  echo -e "Uploads sync took: ${C_ORN}$(readable_time $((SYNC_UPLOAD_TIME - SYNC_END_TIME)))${C_OFF}"
fi
